### ISSUE TITLE
Array text improvements

### ISSUE THREAD

**Issue by PrimaIVoid** [julelang/manual#9]
On page: https://manual.jule.dev/common-concepts/arrays.html

> Index system is simple. Starts at 0 and continue step by step, it is never not be negative and float.

"it is never not be negative and float" this sounds confusing. I think something better would be:
Negative and floating indexes are considered invalid / not allowed

> Arrays is use indexes to access elements and assignment.

Remove the "is"

> First statement is declares our array.

Remove the "is" - The first statement declares our array.

> Multidimensional arrays is array storing arrays.

A Multidimensional array is an array storing arrays.

**Comment by mertcandav** [comment]
LGTM. Thanks for your contribution.
